from pathlib import Path
import re

START='<!-- CONTENT-STRENGTHENING-WAVE3-START -->'
END='<!-- CONTENT-STRENGTHENING-WAVE3-END -->'
STYLE='''<style>.deepHelp3{padding:58px 0;background:#fff;border-top:1px solid #eee8df}.deepHelp3Inner{max-width:850px}.deepHelp3 h2{font:2.35rem/1.08 Georgia,"Times New Roman",serif;font-weight:400;color:#183024;margin:42px 0 14px}.deepHelp3 h2:first-of-type{margin-top:0}.deepHelp3 p{font-size:1rem;line-height:1.76;color:#364039;margin:0 0 1.22em}.deepHelp3 a{color:#294533;font-weight:800;text-underline-offset:2px}.deepScripture3{background:#f6f1e8;border-left:3px solid #ad823d;padding:20px 23px;margin:23px 0 28px;font:1.08rem/1.65 Georgia,"Times New Roman",serif;color:#20372a}.deepScripture3 small{display:block;margin-top:7px;font:700 .68rem/1.4 Arial,sans-serif;letter-spacing:.1em;text-transform:uppercase;color:#87683a}.scriptureList3{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.scriptureItem3{background:#f8f5ef;border:1px solid #ded8cd;padding:20px}.scriptureItem3 strong{display:block;font-size:.7rem;letter-spacing:.11em;text-transform:uppercase;color:#87683a;margin-bottom:7px}.scriptureItem3 p{font:1rem/1.55 Georgia,"Times New Roman",serif;color:#20372a;margin:0}@media(max-width:760px){.scriptureList3{grid-template-columns:1fr}.deepHelp3 h2{font-size:2rem}}</style>'''

FORGIVE=STYLE+'''<section class="deepHelp3"><div class="wrap"><div class="deepHelp3Inner"><p class="eyebrow">Going deeper</p>
<h2>How do you forgive someone who never apologized?</h2><p>Forgiveness becomes especially difficult when the person who hurt you has not owned what they did. Scripture calls believers away from personal vengeance, but that does not require pretending the wound was small or waiting for the offender to deserve mercy. Forgiveness begins with releasing your right to personally make them pay and entrusting justice to God.</p><div class="deepScripture3">“Dearly beloved, avenge not yourselves... Vengeance is mine; I will repay, saith the Lord.”<small>Romans 12:19 · KJV</small></div><p>If that is where you are stuck, <a href="/answer-21">How do I forgive someone who never apologized?</a> goes directly to that question.</p>
<h2>Does forgiveness mean reconciliation?</h2><p>No. Forgiveness and reconciliation are related, but they are not identical. Reconciliation is relational and normally requires truth, repentance, safety, and a willingness from both people to rebuild what was broken. You can forgive someone before trust has been restored.</p><p>That distinction matters because people sometimes use “forgive” to pressure wounded people into immediate access, closeness, or trust. Scripture never requires wisdom to disappear in the name of grace. <a href="/answer-22">Does forgiveness mean I have to let them back in?</a> explores that difference more carefully.</p>
<h2>Can I forgive and still have boundaries?</h2><p>Yes. Boundaries can be an expression of wisdom rather than bitterness. Forgiveness addresses the debt in your heart before God; boundaries address what access is wise in the relationship. In some situations, love may involve distance, accountability, consequences, or refusing to return to an unsafe pattern.</p>
<h2>What if I still feel angry after I forgive?</h2><p>Forgiveness can be a decision that must be revisited emotionally. The return of pain does not always mean forgiveness was fake. A memory, anniversary, conversation, or new discovery may reopen the wound. When that happens, you may need to hand the same debt back to God again rather than treating the recurrence of emotion as failure.</p>
<h2>Am I just as guilty because I am a sinner too?</h2><p>All of us need grace, but universal sinfulness does not erase specific responsibility. Saying “everyone sins” should never be used to flatten the difference between ordinary failure and serious betrayal, abuse, deception, or harm. <a href="/answer-12">Am I just as guilty as the person who hurt me?</a> addresses that confusion directly.</p>
<h2>Four Scriptures for forgiveness and relational hurt</h2><div class="scriptureList3"><div class="scriptureItem3"><strong>Romans 12:19</strong><p>“Vengeance is mine; I will repay, saith the Lord.”</p></div><div class="scriptureItem3"><strong>Ephesians 4:32</strong><p>“...forgiving one another, even as God for Christ’s sake hath forgiven you.”</p></div><div class="scriptureItem3"><strong>Romans 12:18</strong><p>“If it be possible, as much as lieth in you, live peaceably with all men.”</p></div><div class="scriptureItem3"><strong>Proverbs 4:23</strong><p>“Keep thy heart with all diligence...”</p></div></div></div></div></section>'''

DOUBT=STYLE+'''<section class="deepHelp3"><div class="wrap"><div class="deepHelp3Inner"><p class="eyebrow">Going deeper</p>
<h2>Is it wrong for a Christian to doubt?</h2><p>Doubt is not automatically unbelief. The Bible includes people who asked difficult questions, struggled to understand, and needed evidence. Thomas doubted the resurrection and Jesus met him. A desperate father prayed, “Lord, I believe; help thou mine unbelief.” Honest questions can become part of a maturing faith when they are brought into the light rather than hidden in shame.</p><div class="deepScripture3">“Lord, I believe; help thou mine unbelief.”<small>Mark 9:24 · KJV</small></div><p>If you fear that doubt itself proves you were never saved, begin with <a href="/answer-24">Can Christians have doubts?</a></p>
<h2>What if my doubts started because of church hurt?</h2><p>That is an important distinction to make. A church leader, Christian institution, family culture, or ministry can misrepresent Christ. When someone hurts you in God’s name, it can become difficult to separate what Jesus actually taught from what someone attached to His name.</p><p>You do not need to minimize church hurt in order to take Jesus seriously. But before rejecting Christianity, it is worth asking whether you are rejecting Christ Himself or a distorted version of Him. <a href="/answer-23">Am I walking away from God, or from something else wearing His name?</a> is built around that question.</p>
<h2>Is deconstruction always the same as leaving the faith?</h2><p>No. People use the word <em>deconstruction</em> in different ways. Sometimes it means examining inherited beliefs, separating biblical convictions from cultural assumptions, or questioning teachings that were never well grounded. Sometimes it becomes a path toward rejecting Christianity altogether. The label matters less than the direction: Are you honestly testing what is true, or only dismantling without rebuilding?</p>
<h2>How should I handle questions I am afraid to ask?</h2><p>Bring them into the light. Write them down. Separate intellectual questions from emotional wounds. Find mature Christians who are not threatened by honest inquiry. Read careful sources. Ask what Scripture actually says instead of assuming the loudest Christian voice you heard represented the whole faith.</p>
<h2>Can doubt actually strengthen faith?</h2><p>It can. Questions force borrowed convictions to become examined convictions. A faith that has never been tested may feel simpler, but a faith that has wrestled honestly with difficult questions can become deeper, humbler, and more durable. The goal is not doubt for doubt’s sake. The goal is truth.</p>
<h2>Four Scriptures for doubt and church hurt</h2><div class="scriptureList3"><div class="scriptureItem3"><strong>Mark 9:24</strong><p>“Lord, I believe; help thou mine unbelief.”</p></div><div class="scriptureItem3"><strong>John 20:27</strong><p>Jesus meets Thomas in his doubt and calls him toward belief.</p></div><div class="scriptureItem3"><strong>Acts 17:11</strong><p>The Bereans were commended for searching the Scriptures to test what they heard.</p></div><div class="scriptureItem3"><strong>Psalm 34:18</strong><p>God is near to the brokenhearted, including those wounded by people who used His name.</p></div></div></div></div></section>'''

LINES={
'forgiveness-and-relational-hurt.html':'<strong>You may be asking:</strong><br>How do I forgive someone who never apologized? · Does forgiveness mean reconciliation? · Can I forgive and still have boundaries? · What if I still feel angry?',
'doubt-and-church-hurt.html':'<strong>You may be asking:</strong><br>Is it wrong for a Christian to doubt? · What if church hurt caused my doubts? · Is deconstruction the same as leaving faith? · Can doubt strengthen faith?',
}
BLOCKS={'forgiveness-and-relational-hurt.html':FORGIVE,'doubt-and-church-hurt.html':DOUBT}

def patch(name,block):
 p=Path(name); text=p.read_text(); text=re.sub(re.escape(START)+r'.*?'+re.escape(END)+r'\s*','',text,flags=re.S)
 text,count=re.subn(r'<div class="searchIntent">.*?</div>','<div class="searchIntent">'+LINES[name]+'</div>',text,count=1,flags=re.S)
 if count!=1: raise RuntimeError('Could not update '+name)
 marker='<section class="truthSection">'
 if marker not in text: raise RuntimeError('Missing truth section '+name)
 text=text.replace(marker,START+block+END+'\n'+marker,1); p.write_text(text)

for n,b in BLOCKS.items(): patch(n,b)
print('Strengthened Forgiveness & Relational Hurt and Doubt / Church Hurt.')
