from pathlib import Path

BASE = "https://answers-for-a-broken-heart.vercel.app"
HUB_PATH = "/what-hurts-today"
HUB_URL = BASE + HUB_PATH


def patch_index():
    path = Path("index.html")
    text = path.read_text()

    # Let the crawlable hub use normal browser navigation rather than the homepage SPA router.
    if '!href.startsWith("/what-hurts-today")' not in text:
        text = text.replace(
            '&&!href.startsWith("/answer-")',
            '&&!href.startsWith("/answer-")&&!href.startsWith("/what-hurts-today")',
            1,
        )

    # Primary hub links should go to the real static page.
    text = text.replace('href="?view=hurts"', 'href="/what-hurts-today"')

    # Homepage category shortcuts should land on crawlable sections of the hub.
    replacements = {
        'href="?view=hurts&cat=${encodeURIComponent("Grief & Loss")}"': 'href="/what-hurts-today#grief-loss"',
        'href="?view=hurts&cat=${encodeURIComponent("Doubt & Faith")}"': 'href="/what-hurts-today#doubt-faith"',
        'href="?view=hurts&cat=${encodeURIComponent("Why Did This Happen?")}"': 'href="/what-hurts-today#why-did-this-happen"',
        'href="?view=hurts&cat=${encodeURIComponent("God Feels Far Away")}"': 'href="/what-hurts-today#god-feels-far-away"',
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    path.write_text(text)


def patch_answers():
    for number in range(1, 25):
        path = Path(f"answer-{number:02d}.html")
        if not path.exists():
            continue
        text = path.read_text()
        # This updates header navigation plus JSON-LD breadcrumbs generated by seo.py.
        text = text.replace('/?view=hurts', HUB_PATH)
        text = text.replace(BASE + '/?view=hurts', HUB_URL)
        path.write_text(text)


def patch_sitemap():
    path = Path("sitemap.xml")
    text = path.read_text()
    if HUB_URL not in text:
        root_line = f'  <url><loc>{BASE}/</loc><changefreq>monthly</changefreq><priority>1.0</priority></url>'
        hub_line = f'  <url><loc>{HUB_URL}</loc><changefreq>weekly</changefreq><priority>0.9</priority></url>'
        text = text.replace(root_line, root_line + "\n" + hub_line, 1)
    path.write_text(text)


patch_index()
patch_answers()
patch_sitemap()
print("Crawlable What Hurts Today hub linked from homepage, all 24 answers, breadcrumbs, and sitemap.")
